name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Pipenv
      run: |
        pip install pipenv
        pipenv install

    - name: Install LLVM
      run: sudo apt install libllvm15 llvm-15-dev

    - name: Build & Install Protobuf
      run: |
        git clone https://github.com/protocolbuffers/protobuf.git
        cd protobuf
        git checkout v22.0
        git submodule update --init --recursive
        cmake . -Dprotobuf_BUILD_TESTS=OFF
        cmake --build . --parallel 10
        sudo cmake --install .

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build VCLLVM
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Lit Regression Test
      working-directory: ${{github.workspace}}/build
      run: pipenv run make check
